{{- if .Values.console.customLogo.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8pler-console.fullname" . }}-logo
  labels:
    {{- include "k8pler-console.labels" . | nindent 4 }}
binaryData:
  logo: {{ .Values.console.customLogo.data | default (.Files.Get "files/logo.png" | b64enc) }}
{{- end }}
