{{- if .Values.dex.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8pler-console.dex.fullname" . }}
  labels:
    {{- include "k8pler-console.dex.labels" . | nindent 4 }}
---
# Dex's "kubernetes" storage backend keeps its runtime state (auth requests,
# refresh tokens, etc.) as CRs it manages itself, in-cluster.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "k8pler-console.dex.fullname" . }}
  labels:
    {{- include "k8pler-console.dex.labels" . | nindent 4 }}
rules:
  - apiGroups: ["dex.coreos.com"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["create", "get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "k8pler-console.dex.fullname" . }}
  labels:
    {{- include "k8pler-console.dex.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "k8pler-console.dex.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "k8pler-console.dex.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
