{{- if and (eq .Values.auth.type "oidc") .Values.auth.oidc.clientSecret (not .Values.auth.oidc.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8pler-console.fullname" . }}-oidc
  labels:
    {{- include "k8pler-console.labels" . | nindent 4 }}
type: Opaque
stringData:
  client-secret: {{ .Values.auth.oidc.clientSecret | quote }}
{{- end }}
